# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
cache: packages
r:
  - oldrel
  - release
  - devel

env:
  global:
    - MAKEFLAGS="-j 2"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9
    packages:
      - clang-format-3.9

before_install:
  - ln -s /usr/bin/clang-format-3.9 clang-format
  - PATH=.:$PATH travis/check_format.sh

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
